import java.util.Scanner;

//interface vehicle
//{
//    int max_speed = 60;
//    int get_speed();
//    {}
//        void set_speed(int n)
//        {
//            System.out.println("Hello from interface");
//        }
//}
//class car implements vehicle
//{
//    int get_speed()
//    {
//        System.out.println("Car Speed");
//    }
//}

public class Exercise {

    public static void main(String[] args) {
//        Scanner sc = new Scanner(System.in);
//        int a = sc.nextInt();
//        int b = sc.nextInt();
//        try{
//            //is exception occur remaining line as it is and it goes to catch
//            System.out.println(a/b);
//            System.out.println(a+b);
//        }
//        catch(ArithmeticException e){
//            System.out.println("  ");
//        }
//        System.out.println("Hello World");
//    }

//        int i;
//        int[] arr = {1,2,3,34,6,8};
//        Scanner sc = new Scanner(System.in);
//        System.out.println("Enter any index : ");
//        i = sc.nextInt();
//        try
//        {
//            System.out.println(arr[i]);
//        }
//        catch(ArrayIndexOutOfBoundsException e)
////                catch(Exception e) any exception can be handle
//        {
//            System.out.println("You are Enter out of index of given array");
//        }
        /*
        nested try => try ke andar try and also catch because of if we consider 10 line  if line5 to 7 has some error
        so it skip all but it will be not occur when you use nested try because it skip only error line
         */
//        int a,b,arr[];
//        Scanner sc = new Scanner(System.in);
//        System.out.println("Provide two integer");
//        a = sc.nextInt();
//        b = sc.nextInt();
//        try{
//            System.out.println("a/b = "+a/b);
//            arr = new int[a/b];
//            for (int i=0;i<4;i++)
//                arr[i]=i/(i-1);
//            System.out.println("inside of inner first try block");
//        }
//        catch(ArrayIndexOutOfBoundsException ae)
//        {
//            System.out.println("Array Error");
//            System.out.println("Out of outer first try block");
//        }
//        catch(ArithmeticException ae)
//        {
//            System.out.println("Number Error");
//        }
//
//        System.out.println("Hello World");


        }
}